### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rennerr**
Escape greater than and less than chars so they display

### CODE REVIEW

**Comment by rennerr** [comment]
@paul-hammant @maurotalevi @pmcfadden please review and merge if acceptable, thanks.

**Comment by paul-hammant** [comment]
@rennerr does the tutorial work for you as is in 2018 ?

**Comment by rennerr** [comment]
@paul-hammant as far as I have gone through the tutorial, yes.  The code is out of synch with the website, but that is expected as the website has changed.

**Comment by paul-hammant** [comment]
I think my view was that I'd try to keep it in sync with the website. A lot of time has passed though. I'm going to delete the FirefoxWebDriverProvider class I think - too incompatible with the directions for FirefoxDriver itself.

**Comment by paul-hammant** [comment]
Try jbehave-web again (clone; mvn install), then depend on 4.0-SNAPSHOT in your project. Let me know how that goes.

**Comment by rennerr** [comment]
@paul-hammant I cloned and installed https://github.com/jbehave/jbehave-web, updated the pom files in https://github.com/jbehave/jbehave-tutorial to use _\<jbehave.web.version\>4.0-SNAPSHOT_ then ran the tutorial with command **mvn clean install -Pstable**, but I still get errors indicating web page elements can't be found.  Attached is the output.  Note I am on windows 10, I had to change the pom files to use _\<selenium.version\>2.53.1_ in order for my version of firefox 47.0.1 to display the website.  From my perspective, I was able to get from the tutorials what I needed even with these issues.
[out.txt](https://github.com/jbehave/jbehave-tutorial/files/2037109/out.txt)

**Comment by paul-hammant** [comment]
Good to hear. I'll have a look at the tutorial and see if it can be updated.

**Pull request merged**
